version: "3"
name: kitchenowl
services:
  front:
    container_name: kitchenowl-frontend
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - back
  back:
    container_name: kitchenowl-backend
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=PLEASE_CHANGE_ME
    volumes:
      - "${HOST_PATH}:/data"